### ISSUE TITLE
Support Rover solar charge controllers

### ISSUE THREAD

**Issue by mavenius** [mavenius/renogy-bt-esphome#3]
Port https://github.com/cyrils/renogy-bt/blob/main/renogybt/RoverClient.py to esphome

**Comment by mavenius** [comment]
Instead of porting the code over, just grab the log output from running the rover client and rebuild the payload (subbing in the device Id and checksum.)

**Comment by riker65** [comment]
> Port https://github.com/cyrils/renogy-bt/blob/main/renogybt/RoverClient.py to esphome

Hi, is there a code for ported Python? I am not experienced enough to understand it and migrate it myself.

**Comment by mavenius** [comment]
@riker65 I'm manually converting the Python requests and responses into ESPHome/C++ to port over the functionality.

**Comment by riker65** [comment]
Great 
Will check and try to understand 

Thx

**Comment by riker65** [comment]
I tried to understand but failed:

how to enhance BTW these C++ functions (GetBatteryRequest and HandleBatteryData) to read a register for voltage hold in 0101 Register . 

MAybe you could guide a little and just start with one register for voltage of controller. Than I could elaborate a little more.

I am a C++ dummy ...

Wondering why it is so complicated.
There is similar function for modbus controller.
[https://community.home-assistant.io/t/renogy-wander-with-esphome/385909/21](url)
`platform: modbus_controller
modbus_controller_id: renogy_wanderer
name: “Battery Volts”
id: battery_volts

register_type: read
address: 0x101
unit_of_measurement: “V”
value_type: U_WORD`

unfortunately no similar implementation for BLE_Client

**Comment by riker65** [comment]
Hi I am trying to migrate your request to the rover, with different modbus registers.

I am wondering about your implementation

why do you start with hex 13B2 (Decimal 5042) with the vector? 
I think 5042 is referencing current
`    int16_t current;
    std::memcpy(&current, &x[2], sizeof(current));`
but &2 is 5044 should be remaining capacity

`vector<uint8_t> GetBatteryRequest(uint8_t batteryNumber) {
//    vector<uint8_t> dataBytes = { batteryNumber, 0x03, 0x13, 0xB2, 0x00, 0x06 };
// from chat hex 0100 to 0122 this should be 
	 vector<uint8_t> dataBytes = { batteryNumber, 0x03, 0x01, 0x00, 0x00, 0x23 };`


voltage looks good but I can not confirm.

Migrating to Rover charger I did
	 vector<uint8_t> dataBytes = { batteryNumber, 0x03, 0x01, 0x00, 0x00, 0x23 };`

but with hex 101 I should get voltage from 
    uint16_t voltage;
    std::memcpy(&voltage, &x[1], 2);

but value is not correct.


Any ideas what I need to adjust?

Thanks

**Comment by riker65** [comment]
I had to change the vector for the charger
this one is working 	for normal information
 vector<uint8_t> dataBytes = { batteryNumber, 0x03, 0x01, 0x00, 0x00, 0x23 };

for flashed history another vector and function is needed

`    // Parse the current
    int16_t current;
//    std::memcpy(&current, &x[3], sizeof(current));
    std::memcpy(&current, &x[7], 2);
    current = ntohs(current); // Convert from network byte order to host byte order
    ESP_LOGD("HandleBatteryData  current   x7-2!!!!", "current: %d", current);
    // Parse the voltage
    uint16_t voltage;
    std::memcpy(&voltage, &x[5], 2);
    voltage = ntohs(voltage); // Convert from network byte order to host byte order
    ESP_LOGD("HandleBatteryData  x5,2: VOLTAGE ", "voltage: %d", voltage);`

**Comment by mavenius** [comment]
Sweet!

I actually have a converted version of the Rover logic running on an ESP,
and it looks good so far:





I'll update the repo ASAP; likely tomorrow.

**Comment by mavenius** [comment]
Sorry for the delay; life got in the way. I was finally able to circle back on this.
