### ISSUE TITLE
reference Solarthing

### ISSUE THREAD

**Issue by riker65** [mavenius/renogy-bt-esphome#6]
Hi
It might be very helpful to have a look here:

https://github.com/wildmountainfarms/solarthing

he did a lot of renogy implementation and also configuration as a reference

could not create a discussion, but just an issue.

**Comment by mavenius** [comment]
This looks really cool! At first glance, I don't see Bluetooth as a way to configure it, but I'll keep looking. 

Thanks!

**Comment by riker65** [comment]
unfortuantely it is not bluetooth 
but a really good java implementation with a lot of features

Issue is, parallel usage of cable and BLE does block the Renogy device

**Comment by mavenius** [comment]
Thanks for looking into it!
